data: out_scale/energies_forces_dipoles_train.npz
valid_data: null
ckpt_dir: ./ckpts/dcm-test
tag: dcm1
seed: 42
batch_size: 50
num_epochs: 50
learning_rate: 0.005
optimizer: adamw
energy_weight: 10.0
forces_weight: 52.91
dipole_weight: 27.21
charges_weight: 14.39
charges: true
include_electrostatics: true
objective: valid_loss
n_train: 10000
n_valid: 2000
features: 32
max_degree: 1
num_basis_functions: 32
num_iterations: 2
n_res: 3
cutoff: 6.0
max_atomic_number: 35
use_energy_bias: true
use_pbc: false
zbl: true
save_every_epoch: true
print_freq: 1
total_charge: 0.0
