data: /mmhome/boittier/home/mmml_tutorial/acodcm/out/splits/aco/lc_n3200_r3_no_outliers/train.npz
valid_data: /mmhome/boittier/home/mmml_tutorial/acodcm/out/splits/aco/lc_n3200_r3_no_outliers/valid.npz
n_train: 0
n_valid: 0
ckpt_dir: /mmhome/boittier/home/mmml_tutorial/acodcm/ckpts/learning_curve/e1000/aco/n3200/r3_clean
tag: aco1_n3200_r3_clean
seed: 3042
batch_size: 25
num_epochs: 1000
learning_rate: 0.001
optimizer: amsgrad
energy_weight: 1000.0
forces_weight: 100.0
dipole_weight: 1.0
charges_weight: 1.0
charges: true
include_electrostatics: false
max_atomic_number: 35
features: 32
max_degree: 2
num_basis_functions: 32
num_iterations: 3
n_res: 3
cutoff: 4.0
zbl: true
num_atoms: 20
