batch_args_dict: null
batch_method: default
batch_size: 50
best: false
charges: true
charges_weight: 14.39
ckpt_dir: ./ckpts/dcm-test
config: null
conversion: null
cutoff: 6.0
data: ./out/splits/dcm/energies_forces_dipoles_train.npz
data_keys: null
debug: false
dipole_weight: 27.21
early_stop_patience: null
efa: false
energy_weight: 10.0
features: 32
forces_weight: 52.91
include_electrostatics: true
init_params: null
learning_rate: 0.005
max_atomic_number: 35
max_degree: 1
model: null
n_res: 3
n_train: 10000
n_valid: 2000
num_atoms: null
num_basis_functions: 32
num_epochs: 1200
num_iterations: 2
objective: valid_loss
optimizer: adamw
print_freq: 1
profile_epoch_timing: false
quiet: false
restart: null
rot_augment: false
rot_perturbation: 1.0
save_every_epoch: true
schedule_fn: null
seed: 42
tag: dcm1
total_charge: 0.0
transform: null
use_energy_bias: true
use_pbc: false
valid_data: null
zbl: true
